### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "full_name": "Habib Almaula",
  "email": "yoga@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yoga@gmail.com",
  "password": "123456"
}



### GET All Categories
GET http://localhost:3000/api/categories
Accept: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0Nzg0ODcsImlhdCI6MTcyNTI2MjQ4Nywic3ViIjoiMGY5ZDdjZmUtNzIyZC00MDgyLWJlZWYtOWU3MzE1Y2ExNDc3In0.pa91raqtxj3kGF6aIhhMUwnhSOp6gvWOQmG07cgZUII



### Create Category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": ""
}

### Get Category by ID
GET http://localhost:3000/api/categories/100
Accept: application/json


### Update Category
PUT http://localhost:3000/api/categories/4
Accept: application/json
Content-Type: application/json

{
  "name": "Category 4 Updated"
}

### Delete Category
DELETE http://localhost:3000/api/categories/2
Accept: application/json
Content-Type: application/json
